### ISSUE TITLE
Pinterest App Linking to AMP Pages

### ISSUE THREAD

**Issue by fexybob** [pinterest/widgets#75]
Recently we've noticed that the Pinterest App is sending traffic to our AMP pages even if the original pin was from a widget on a regular non-AMP page. Currently our AMP pages aren't as robust as our regular pages and don't monetize as well either. Is there anything we can do to make it direct to the regular canonical URL and not the AMP URL until we are at least able to make our AMP pages more robust?

**Comment by kentbrew** [comment]
This does not seem like something I'm going to be able to address with pinit.js. Without looking at some of your AMP pages I'm not going to be able to help; please re-open with URLs if it's still a problem.

**Comment by clyons** [comment]
I know that this issue is closed. I just wanted to comment that it is not possible to stop Pinterest from serving the AMP version of your pages to users of its mobile app.

Pinterest discusses its engineering decision here:
https://medium.com/@Pinterest_Engineering/building-a-faster-mobile-web-experience-with-amp-a73c651ded7

The only way to prevent Pinterest from serving your AMP pages would be to stop publishing AMP pages and redirect the old AMP pages to their canonical URL.
